
services:
  rstudio:
    image: ghcr.io/shafayetshafee/within-group-gcomp:latest
    container_name: within-group-gcomp
    ports:
      - "8787:8787"
    environment:
      DISABLE_AUTH: "true"
    restart: unless-stopped
